# Generated by Django 4.2.9 on 2026-06-02 23:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reservations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('capacity_score', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('preference_score', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('utilization_score', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('historical_score', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('reasoning', models.JSONField(default=dict)),
                ('alternatives_data', models.JSONField(default=list)),
                ('alternative_slots', models.JSONField(default=list)),
                ('algorithm_version', models.CharField(default='v2.0', max_length=20)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('was_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Recommendation',
                'db_table': 'reservations_ai_recommendation',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(default=reservations.models.generate_reservation_id, editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_whatsapp', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('guest_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('special_requests', models.TextField(blank=True, max_length=1000)),
                ('occasion', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show'), ('modified', 'Modified')], default='pending', max_length=15)),
                ('source', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile App'), ('phone', 'Phone'), ('admin', 'Admin Panel')], default='web', max_length=10)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('ai_table_assigned', models.BooleanField(default=False)),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('confirmation_sent', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'reservations_reservation',
                'ordering': ['-reservation_date', '-reservation_time'],
            },
        ),
        migrations.CreateModel(
            name='ReservationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show'), ('modified', 'Modified')], max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reservations_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('guest_count', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservations_waitlist',
                'ordering': ['created_at'],
            },
        ),
    ]
